services:
  - type: web
    name: fastapi-tts
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg poppler-utils
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
